-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Data

local Facing = {
    Up = 0,
    Down = 1,
    Left = 2,
    Right = 3,
}

return Facing -- return the module