// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Zophos.Data
{

public enum Facing : sbyte
{
  Up = 0,
  Down = 1,
  Left = 2,
  Right = 3,
};


}
